#!/usr/bin/env bash

[[ $# -ne 1 ]] && echo "Usage: $(basename $0) /path/to/script" && exit 1

script=${1}

if cmp -s <(${script}) ./test_data; then
    echo "OK"
else
    echo "FAILED"
    exit 1
fi

# Time
echo
echo "Testing average time"
echo
perf stat -n -r 10 -B ${1} >/dev/null
