#!/usr/bin/env bash

set -eo pipefail

[[ "${TRACE:-}" ]] && set -x


main() {
    [[ $# -eq 0 ]] && echo "Usage: $(basename $0) /path/to/script" && exit 1
    local script=("$@")
    
    if cmp -s <("${script[@]}") ./test_data; then
        echo "OK"
    else
        echo "FAILED"
        exit 1
    fi
    
    # Time
    echo
    echo "Testing average time"
    echo
    perf stat -n -r 10 -B "${script[@]}" >/dev/null
}

main "$@"
